name: build and publish

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run tests
        run: cargo test --verbose
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc-mingw-w64-x86-64
          rustup +nightly target add x86_64-pc-windows-gnu
          rustup +nightly target add x86_64-unknown-linux-gnu
          rustup +nightly target add x86_64-apple-darwin
          mkdir dist
          mkdir builds
      - name: Build Win64
        run: |
          cargo +nightly rustc --bin lupinas-lullaby --release --verbose --target=x86_64-pc-windows-gnu -- -C linker=x86_64-w64-mingw32-gcc
          mkdir builds/lupinas-lullaby-win64
          cp target/x86_64-pc-windows-gnu/release/lupinas-lullaby.exe builds/lupinas-lullaby-win64/lupinas-lullaby-win64.exe
          tar -C builds -czvf dist/lupinas-lullaby-win64.tar.gz lupinas-lullaby-win64
      - name: Build Linux
        run: |
          cargo +nightly rustc --bin lupinas-lullaby --release --verbose --target=x86_64-unknown-linux-gnu
          mkdir builds/lupinas-lullaby-linux
          cp target/x86_64-unknown-linux-gnu/release/lupinas-lullaby builds/lupinas-lullaby-linux/lupinas-lullaby-linux
          tar -C builds -czvf dist/lupinas-lullaby-linux.tar.gz lupinas-lullaby-linux
      - name: Install Mac OS dependencies
        run: |
          git clone https://github.com/tpoechtrager/osxcross
          cd osxcross
          sudo tools/get_dependencies.sh
          wget -nc https://s3.dockerproject.org/darwin/v2/MacOSX10.10.sdk.tar.xz
          mv MacOSX10.10.sdk.tar.xz tarballs/
          UNATTENDED=yes OSX_VERSION_MIN=10.7 ./build.sh
      - name: Build Mac OS
        run: |
          export PATH="$(pwd)/osxcross/target/bin:$PATH"
          export LIBZ_SYS_STATIC=1
          export CC=o64-clang
          export CXX=o64-clang++
          cargo +nightly build --bin lupinas-lullaby --release --verbose --target x86_64-apple-darwin
          mkdir builds/lupinas-lullaby-macos
          cp target/x86_64-apple-darwin/release/lupinas-lullaby builds/lupinas-lullaby-macos/lupinas-lullaby-macos
          tar -C builds -czvf dist/lupinas-lullaby-macos.tar.gz lupinas-lullaby-macos
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/lupinas-lullaby-win64.tar.gz
            dist/lupinas-lullaby-linux.tar.gz
            dist/lupinas-lullaby-macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish npm package
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_ACCESS_TOKEN" > ".npmrc"
          npm publish
      - name: Publish cargo package
        env:
          CARGO_ACCESS_TOKEN: ${{ secrets.CARGO_ACCESS_TOKEN }}
        run: |
          cargo login "$CARGO_ACCESS_TOKEN"
          cargo publish
